import { HttpErrorResponse, HttpInterceptorFn } from '@angular/common/http';
import { catchError, throwError } from 'rxjs';
import { ToastrService } from '../../shared/ui/toastr/services/toastr.service';
import { inject } from '@angular/core';

export const errorInterceptor: HttpInterceptorFn = (req, next) => {
  const toastr = inject(ToastrService);

  return next(req).pipe(
    catchError((err: HttpErrorResponse) => {
      let errorMsg = 'حدث خطأ غير متوقع، يرجى المحاولة لاحقًا.';

      if (err.error instanceof ErrorEvent) {
        // Error من جهة العميل (مشكلة في الاتصال)
        errorMsg = `خطأ في الاتصال: ${err.error.message}`;

      
      } else {

        if (err.error?.detail) {
          errorMsg = err.error.detail;
        } else if (err.error?.message) {
          errorMsg = err.error.message;
        }else if(err.error.errors && err.error.errors.length > 0 && Array.isArray(err.error.errors)){
          err.error.errors.detail.forEach((error:any) => {
            const message = error;
            

            toastr.show(message, 'error');
            
          });
          
        } else if(err.error.detail){
          errorMsg = err.error.detail

          toastr.show(errorMsg, 'error');

        }
        
        else {
          // لو مافيش code أو message، نستخدم switch على status
          switch (err.status) {
            case 400:
              errorMsg = 'طلب غير صحيح (Bad Request)';
              break;
            case 401:
              errorMsg = 'غير مصرح لك بالدخول. يرجى تسجيل الدخول.';
              break;
            case 403:
              errorMsg = 'ليس لديك صلاحية للوصول إلى هذا المورد.';
              break;
            case 404:
              errorMsg = 'العنصر المطلوب غير موجود.';
              break;
            case 500:
              errorMsg = 'خطأ داخلي في الخادم.';
              break;
            default:
              errorMsg = `حدث خطأ رقم ${err.status}`;
          }
        }
      }
      // ✅ عرض الرسالة في التوستر
      toastr.show(errorMsg, 'error');

      // ✅ ارجع الخطأ بشكل سليم لـ RxJS
      return throwError(() => err);
    })
  );
};
